kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "pulp-build" 
spec:
  runPolicy: "Serial" 
  source: 
    git:
      uri: "https://github.com/bmbouter/pulp3-openshift"
  strategy: 
    dockerStrategy:
      dockerfilePath: pulp_ansible/Dockerfile
  output: 
    to:
      kind: "ImageStreamTag"
      name: "pulp_worker:latest"
