apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "pulp3-filesystem"
spec:
  accessModes:
    - "ReadWriteOnly"
  resources:
    requests:
      storage: "2Gi"
  volumeName: "pulp3-filesystem"
